# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flags
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flags
  template:
    metadata:
      labels:
        app: flags
    spec:
      containers:
      - name: flags
        # Replace $GCLOUD_PROJECT with your project ID
        image: eu.gcr.io/flags-293518/image1
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"