name: Build and deploy to GKE

on:
  push:
    branches:
    - deployment

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - run: echo "${{ secrets.GKE_SA_KEY }}"| base64 -d > key-file.json
      - run: cat key-file.json
      - run: |-
          gcloud auth activate-service-account github@flags-293518.iam.gserviceaccount.com --key-file=key-file.json

      - name: Deploy
        run: ./gcr.sh
